console.log("Feat ");
console.log("Fix ");
console.log("Docs ");
console.log("Style ");
console.log("Refactor ");
console.log("Test ");
console.log("Chore ");
console.log("Design");
console.log("Add");
console.log("Rename");
console.log("Remove");
console.log("Clean");
